### ISSUE TITLE
django-rest, server expansion

### ISSUE THREAD

**Issue by Ruslan1999w** [Ruslan1999w/Blog#12]
- [x] Вьюха комментов с методами: list, create, update,delete

- [x] ArticleViewSet добавить в serializer Post, чтобы он возвращал id_post, по которому в дальнейшем будет переход по ссылке http://some_adess/articles/pk=id_postz

- [x] ArticleViewSet листинг, должен возвращать помимо названия статьи, описания, кол-во лайков, еще и теги, фоновую картинку статьи, категорию.

- [x] UserRetrieve - модифицировать, чтобы он возвращал все комментарии пользователя, вместе с комментируемыми книгами и все лайки пользователя, также с книгами

**Comment by TwoXowT** [comment]
о какиъ книгах идет речь
